name: holodex_plus_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-279.2.beta <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  http: ^1.2.1
  melos: ^4.1.0
  url_launcher: ^6.2.4

dev_dependencies:
  custom_lint: ^0.6.2
  flutter_test:
    sdk: flutter
  solid_lints: ^0.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/css/
    - assets/images/
    - assets/scripts/
